### ISSUE TITLE
Keep up The Great Work Guys 

### ISSUE THREAD

**Issue by Pham-Vincent** [Jairik/MOVE4WELLNESS-Android-App#1]
![image](https://github.com/Jairik/MOVE4WELLNESS-Android-App/assets/156252560/a4106fb2-b203-4d28-ac24-d6ef06774ae2)

**Comment by Jairik** [comment]
![thumb-up-winking-emoticon-vector-21534979](https://github.com/Jairik/MOVE4WELLNESS-Android-App/assets/148400231/ca294195-2656-4544-9e6e-85eda058a16f)
